<a href="https://colab.research.google.com/github/vladgnez0/Diskretka/blob/main/KCC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Исходная матрица смежности
S = np.array([
    [0, 1, 0, 1, 0, 0],
    [0, 0, 1, 0, 0, 1],
    [0, 0, 0, 0, 1, 0],
    [0, 0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0, 0],
    [1, 0, 0, 0, 1, 0]
])

# Возведение матрицы S в степени
S2 = np.linalg.matrix_power(S, 2)
S3 = np.linalg.matrix_power(S, 3)
S4 = np.linalg.matrix_power(S, 4)
S5 = np.linalg.matrix_power(S, 5)
S6 = np.linalg.matrix_power(S, 6)

E = np.array([[1, 0, 0, 0, 0, 0],
 [0, 1, 0, 0,0, 0],
 [0, 0, 1, 0, 0, 0],
 [0, 0, 0,1, 0, 0],
 [0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0,0, 1]])
B=E+S+S2+S3+S4+S5+S6

# Вывод матриц
print("Матрица S^2:")
print(S2)
print("Матрица S^3:")
print(S3)
print("Матрица S^4:")
print(S4)
print("Матрица S^5:")
print(S5)
print("Матрица S^6:")
print(S6)
print("Сумма степеней матрицы E:")
print(E)
print("B:")
print(B)

# Вычисление матриц C и L
C = (B > 0).astype(int)
L = C.T

# Вывод матриц C и L
print("Матрица C:")
print(C)
print("Матрица L:")
print(L)

# Построение итоговой матрицы F как произведение C и L
F = np.dot(C, L)

# Вывод итоговой матрицы F
print("Итоговая матрица F:")
F = (F >np.max(F)-1 ).astype(int)
print(F)

# Проверка компонент сильной связности
def find_strongly_connected_components(F):
    n = F.shape[0]
    components = []
    visited = [False] * n

    for i in range(n):
        if not visited[i]:
            component = []
            for j in range(n):
                if np.array_equal(F[i], F[j]) and not visited[j]:
                    component.append(j+1)
                    visited[j] = True
            components.append(component)

    return components

components = find_strongly_connected_components(F)
print("Компоненты сильной связности:")
print(components)


Матрица S^2:
[[0 0 2 0 0 1]
 [1 0 0 0 2 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 1 0 0 0]
 [0 1 0 2 0 0]]
Матрица S^3:
[[1 0 0 0 3 0]
 [0 1 0 3 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 3 0 0 1]]
Матрица S^4:
[[0 1 0 4 0 0]
 [0 0 4 0 0 1]
 [0 0 0 0 1 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [1 0 0 0 4 0]]
Матрица S^5:
[[0 0 5 0 0 1]
 [1 0 0 0 5 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 1 0 0 0]
 [0 1 0 5 0 0]]
Матрица S^6:
[[1 0 0 0 6 0]
 [0 1 0 6 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 6 0 0 1]]
Сумма степеней матрицы E:
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]
B:
[[3 2 7 5 9 2]
 [2 3 5 9 7 2]
 [0 0 3 2 2 0]
 [0 0 2 3 2 0]
 [0 0 2 2 3 0]
 [2 2 9 7 5 3]]
Матрица C:
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [0 0 1 1 1 0]
 [0 0 1 1 1 0]
 [0 0 1 1 1 0]
 [1 1 1 1 1 1]]
Матрица L:
[[1 1 0 0 0 1]
 [1 1 0 0 0 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 0 0 0 1]]
Итоговая матрица F:
[[1 1 0 0 0 1]
 [1 1 0 0 0 1]
 [0 0 0 0 0 0]
